spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 'localhost:9092'
          autoCreateTopics: true
          replicationFactor: 1
        deserializationExceptionHandler: logAndContinue
        bindings:
          notification-input:
            consumer:
              startOffset: latest
              enableDlq: true
              dlqName: register-user_notification-DLQ
              autoCommitOnError: true
              autoCommitOffset: true
              configuration:
                max.poll.records: 100
                max.poll.interval.ms: 1000000
      bindings:
        notification-input:
          destination: register-user_notification
          contenty-type: application/json
          group: notification
          consumer:
            maxAttempts: 1
            concurrency: 5

  mail:
    username: xxxx@gmail.com
    password: xxxxx
    host: smtp.gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
